[package]
name = "inc"


[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full", "test-util"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
serde_derive = "1.0"
tch = {version= "0.15.0" }
torch-sys = {version= "0.15.0", features=["download-libtorch"]}